language: python

before_install:
    - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=$HOME/miniconda3/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -f environment.yml
    - source activate intent-server

script:
    - python3 setup.py install
    - flake8
    - mypy src/main.py

test:
    - python3 setup.py test

notifications:
    email: false
